# Generated by Django 3.0.4 on 2020-04-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('No genre', ' '), ('Alternative', 'Alternative'), ('Blues/R&B', 'Blues/R&B'), ('Books & Spoken', 'Books & Spoken'), ("Children's Music", "Children's Music"), ('Classic Rock', 'Classic Rock'), ('Classic Rock/Rock', 'Classic Rock/Rock'), ('Classical', 'Classical'), ('Country', 'Country'), ('Dance', 'Dance'), ('Easy Listening', 'Easy Listening'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Hip Hop/Rap', 'Hip Hop/Rap'), ('Holiday', 'Holiday'), ('House', 'House'), ('Industrial', 'Industrial'), ('Jazz', 'Jazz'), ('Leftfield', 'Leftfield'), ('New Age', 'New Age'), ('Other', 'Other'), ('Pop', 'Pop'), ('Pop/Rock', 'Pop/Rock'), ('R&B', 'R&B'), ('R&B/Soul', 'R&B/Soul'), ('Religious', 'Religious'), ('Rock', 'Rock'), ('Rock & Roll', 'Rock & Roll'), ('Soundtrack', 'Soundtrack'), ('Techno', 'Techno'), ('Trance', 'Trance'), ('Unclassifiable', 'Unclassifiable'), ('Vocal', 'Vocal'), ('World', 'World')], default=' ', max_length=100)),
            ],
        ),
    ]
