# Generated by Django 3.0.4 on 2020-03-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
