# Generated by Django 3.0.4 on 2020-03-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
