# Generated by Django 3.0.4 on 2020-03-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0006_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='docfile',
        ),
    ]
