# Generated by Django 3.0.4 on 2020-03-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0008_auto_20200325_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
