# Generated by Django 3.0.4 on 2020-03-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0010_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
