# Generated by Django 3.0.4 on 2020-04-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0012_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('No genre', ' '), ('Alternative', 'Alternative'), ('Blues/R&B', 'Blues/R&B'), ('Books & Spoken', 'Books & Spoken'), ("Children's Music", "Children's Music"), ('Classic Rock', 'Classic Rock'), ('Classic Rock/Rock', 'Classic Rock/Rock'), ('Classical', 'Classical'), ('Country', 'Country'), ('Dance', 'Dance'), ('Easy Listening', 'Easy Listening'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Hip Hop/Rap', 'Hip Hop/Rap'), ('Holiday', 'Holiday'), ('House', 'House'), ('Industrial', 'Industrial'), ('Jazz', 'Jazz'), ('Leftfield', 'Leftfield'), ('New Age', 'New Age'), ('Other', 'Other'), ('Pop', 'Pop'), ('Pop/Rock', 'Pop/Rock'), ('R&B', 'R&B'), ('R&B/Soul', 'R&B/Soul'), ('Religious', 'Religious'), ('Rock', 'Rock'), ('Rock & Roll', 'Rock & Roll'), ('Soundtrack', 'Soundtrack'), ('Techno', 'Techno'), ('Trance', 'Trance'), ('Unclassifiable', 'Unclassifiable'), ('Vocal', 'Vocal'), ('World', 'World')], default=' ', max_length=100),
        ),
    ]
